// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Avika.Forum.Model
{
    using Avika.Forum.Model;

    // COArticu
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.0.0")]
    public partial class CoArticu
    {
        public string CodigoArt { get; set; } // codigo_art (Primary key) (length: 15)
        public string DescripArt { get; set; } // descrip_art (length: 30)
        public string CatProdArt { get; set; } // cat_prod_art (length: 3)
        public string UniMedArt { get; set; } // uni_med_art (length: 2)
        public string UniMedVtaArt { get; set; } // uni_med_vta_art (length: 2)
        public decimal? UniConvArt { get; set; } // uni_conv_art
        public string UniMedComArt { get; set; } // uni_med_com_art (length: 2)
        public decimal? PrecioArt { get; set; } // precio_art
        public string TipMatArt { get; set; } // tip_mat_art (length: 3)
        public string CodActArt { get; set; } // cod_act_art (length: 1)
        public string AplicaIvaArt { get; set; } // aplica_iva_art (length: 1)
        public string Descrip2Art { get; set; } // descrip2_art (length: 30)
        public decimal? FacConvArt { get; set; } // fac_conv_art
        public string LocalizaArt { get; set; } // localiza_art (length: 15)
        public string ProvArt { get; set; } // prov_art (length: 4)
        public decimal? GarantArt { get; set; } // garant_art
        public string CodArtProv { get; set; } // cod_art_prov (length: 13)
        public string CodigoBarras { get; set; } // codigo_barras (length: 20)
        public string OrganArt { get; set; } // organ_art (length: 1)
        public string ClasifArt { get; set; } // clasif_art (length: 15)

        public CoArticu()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
