// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Avika.Forum.Model
{
    using Avika.Forum.Model;

    // COBodega
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.0.0")]
    public partial class CoBodega
    {
        public string CodigoBod { get; set; } // codigo_bod (Primary key) (length: 3)
        public string DescripBod { get; set; } // descrip_bod (length: 15)
        public string Direc1Bod { get; set; } // direc1_bod (length: 40)
        public string Direc2Bod { get; set; } // direc2_bod (length: 40)
        public string CiudadBod { get; set; } // ciudad_bod (length: 26)
        public string EstadoBod { get; set; } // estado_bod (length: 4)
        public string CodPostBod { get; set; } // cod_post_bod (length: 10)
        public string PaisBod { get; set; } // pais_bod (length: 20)
        public string Telef1Bod { get; set; } // telef1_bod (length: 20)
        public string Telef2Bod { get; set; } // telef2_bod (length: 20)
        public string Exten1Bod { get; set; } // exten1_bod (length: 4)
        public string Exten2Bod { get; set; } // exten2_bod (length: 4)
        public string FaxBod { get; set; } // fax_bod (length: 20)
        public string EncargadoBod { get; set; } // encargado_bod (length: 40)
        public string PermMovBod { get; set; } // perm_mov_bod (length: 1)
        public string TipoBod { get; set; } // tipo_bod (length: 1)
        public string SubsBod { get; set; } // subs_bod (length: 3)
        public string Serie { get; set; } // serie (length: 1)
        public decimal? Factura { get; set; } // factura
        public decimal? OrdenCompra { get; set; } // orden_compra
        public decimal? Entrada { get; set; } // entrada
        public decimal? Salida { get; set; } // salida
        public decimal? TranInv { get; set; } // tran_inv
        public decimal? Cotizacion { get; set; } // cotizacion

        // Reverse navigation

        /// <summary>
        /// Child CoMovInvs where [COMovInv].[bodega_moi] point to this entity (FK_COMovInv_COBodega)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CoMovInv> CoMovInvs { get; set; } // COMovInv.FK_COMovInv_COBodega

        public CoBodega()
        {
            CoMovInvs = new System.Collections.Generic.List<CoMovInv>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
