// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Avika.Forum.Model
{
    using Avika.Forum.Model;

    // COCatPro
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.0.0")]
    public partial class CoCatPro
    {
        public string CategoriaCap { get; set; } // categoria_cap (Primary key) (length: 3)
        public string DescripCap { get; set; } // descrip_cap (length: 15)
        public decimal? DiasVenCap { get; set; } // dias_ven_cap

        public CoCatPro()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
