// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Avika.Forum.Model
{
    using Avika.Forum.Model;

    // COCentroCostos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.0.0")]
    public partial class CoCentroCosto
    {
        public string Codigo { get; set; } // codigo (Primary key) (length: 5)
        public string Descripcion { get; set; } // descripcion (length: 100)
        public string Variedad { get; set; } // variedad (length: 30)
        public decimal? Ingreso { get; set; } // ingreso
        public decimal? Porcentaje { get; set; } // porcentaje
        public string Cliente { get; set; } // cliente (length: 12)

        public CoCentroCosto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
