// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Avika.Forum.Model
{
    using Avika.Forum.Model;

    // COMovInv
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.0.0")]
    public class CoMovInvConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CoMovInv>
    {
        public CoMovInvConfiguration()
            : this("dbo")
        {
        }

        public CoMovInvConfiguration(string schema)
        {
            ToTable("COMovInv", schema);
            HasKey(x => new { x.FecAsenMoi, x.HoraAsenMoi, x.ModuloMoi, x.PrefDocMoi, x.NumDocMoi, x.NumLineaMoi, x.NumArtMoi, x.BodegaMoi });

            Property(x => x.FecAsenMoi).HasColumnName(@"fec_asen_moi").HasColumnType("decimal").IsRequired().HasPrecision(8,0).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.HoraAsenMoi).HasColumnName(@"hora_asen_moi").HasColumnType("decimal").IsRequired().HasPrecision(6,0).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ModuloMoi).HasColumnName(@"modulo_moi").HasColumnType("char").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(1).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.PrefDocMoi).HasColumnName(@"pref_doc_moi").HasColumnType("char").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(2).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.NumDocMoi).HasColumnName(@"num_doc_moi").HasColumnType("char").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(8).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.NumLineaMoi).HasColumnName(@"num_linea_moi").HasColumnType("decimal").IsRequired().HasPrecision(5,0).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.NumArtMoi).HasColumnName(@"num_art_moi").HasColumnType("char").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(15).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.BodegaMoi).HasColumnName(@"bodega_moi").HasColumnType("char").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(3).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.BodDestMoi).HasColumnName(@"bod_dest_moi").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(3);
            Property(x => x.FecDocMoi).HasColumnName(@"fec_doc_moi").HasColumnType("decimal").IsOptional().HasPrecision(8,0);
            Property(x => x.TipoDocMoi).HasColumnName(@"tipo_doc_moi").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(1);
            Property(x => x.TipoMovMoi).HasColumnName(@"tipo_mov_moi").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(1);
            Property(x => x.NumCteProvMoi).HasColumnName(@"num_cte_prov_moi").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(12);
            Property(x => x.NumVenMoi).HasColumnName(@"num_ven_moi").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(4);
            Property(x => x.CanVieMoi).HasColumnName(@"can_vie_moi").HasColumnType("decimal").IsOptional().HasPrecision(13,4);
            Property(x => x.CantidadMoi).HasColumnName(@"cantidad_moi").HasColumnType("decimal").IsOptional().HasPrecision(13,4);
            Property(x => x.PrecioMoi).HasColumnName(@"precio_moi").HasColumnType("decimal").IsOptional().HasPrecision(13,2);
            Property(x => x.ImporteMoi).HasColumnName(@"importe_moi").HasColumnType("decimal").IsOptional().HasPrecision(13,2);
            Property(x => x.CtoVieMoi).HasColumnName(@"cto_vie_moi").HasColumnType("decimal").IsOptional().HasPrecision(15,6);
            Property(x => x.CtoUniMoi).HasColumnName(@"cto_uni_moi").HasColumnType("decimal").IsOptional().HasPrecision(15,6);
            Property(x => x.CtoPromMoi).HasColumnName(@"cto_prom_moi").HasColumnType("decimal").IsOptional().HasPrecision(15,6);
            Property(x => x.CtoAdiMoi).HasColumnName(@"cto_adi_moi").HasColumnType("decimal").IsOptional().HasPrecision(15,6);
            Property(x => x.UsuarioMoi).HasColumnName(@"usuario_moi").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(10);
            Property(x => x.ComentMoi).HasColumnName(@"coment_moi").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(30);
            Property(x => x.NumEntSalMoi).HasColumnName(@"num_ent_sal_moi").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(8);
            Property(x => x.NumTransMoi).HasColumnName(@"num_trans_moi").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(8);
        }
    }

}
// </auto-generated>
