// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Avika.Forum.Model
{
    using Avika.Forum.Model;

    // COTipMat
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.0.0")]
    public class CoTipMatConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CoTipMat>
    {
        public CoTipMatConfiguration()
            : this("dbo")
        {
        }

        public CoTipMatConfiguration(string schema)
        {
            ToTable("COTipMat", schema);
            HasKey(x => x.TipoTim);

            Property(x => x.TipoTim).HasColumnName(@"tipo_tim").HasColumnType("char").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(3).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.DescripTim).HasColumnName(@"descrip_tim").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(15);
        }
    }

}
// </auto-generated>
