// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Avika.Forum.Model
{
    using Avika.Forum.Model;

    // COTipMat
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.0.0")]
    public partial class CoTipMat
    {
        public string TipoTim { get; set; } // tipo_tim (Primary key) (length: 3)
        public string DescripTim { get; set; } // descrip_tim (length: 15)

        // Reverse navigation

        /// <summary>
        /// Child CoArticus where [COArticu].[tip_mat_art] point to this entity (FK_COArticu_COTipMat)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CoArticu> CoArticus { get; set; } // COArticu.FK_COArticu_COTipMat

        public CoTipMat()
        {
            CoArticus = new System.Collections.Generic.List<CoArticu>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
