// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Avika.Forum.Model
{
    using Avika.Forum.Model;

    // News
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.0.0")]
    public partial class News
    {
        public int Id { get; set; } // Id (Primary key)
        public int CategoryId { get; set; } // CategoryId
        public int CompanyId { get; set; } // CompanyId
        public string Title { get; set; } // Title (length: 300)
        public string Description { get; set; } // Description
        public string UserCreaterId { get; set; } // UserCreaterId (length: 128)
        public System.DateTime DateCreation { get; set; } // DateCreation
        public System.DateTime DatePublished { get; set; } // DatePublished
        public bool Active { get; set; } // Active

        // Reverse navigation

        /// <summary>
        /// Child Companies (Many-to-Many) mapped by table [NewCompanies]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Company> Companies { get; set; } // Many to many mapping
        /// <summary>
        /// Child NewHasPhotoes where [NewHasPhotos].[NewId] point to this entity (FK_NewHasPhotos_News)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<NewHasPhoto> NewHasPhotoes { get; set; } // NewHasPhotos.FK_NewHasPhotos_News

        // Foreign keys

        /// <summary>
        /// Parent Category pointed by [News].([CategoryId]) (FK_News_Categories)
        /// </summary>
        public virtual Category Category { get; set; } // FK_News_Categories

        public News()
        {
            NewHasPhotoes = new System.Collections.Generic.List<NewHasPhoto>();
            Companies = new System.Collections.Generic.List<Company>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
