// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Avika.Forum.DAO
{
    using Avika.Forum.Model;

    // COBodega
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.0.0")]
    public class CoBodegaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CoBodega>
    {
        public CoBodegaConfiguration()
            : this("dbo")
        {
        }

        public CoBodegaConfiguration(string schema)
        {
            ToTable("COBodega", schema);
            HasKey(x => x.CodigoBod);

            Property(x => x.CodigoBod).HasColumnName(@"codigo_bod").HasColumnType("char").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(3).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.DescripBod).HasColumnName(@"descrip_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(15);
            Property(x => x.Direc1Bod).HasColumnName(@"direc1_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(40);
            Property(x => x.Direc2Bod).HasColumnName(@"direc2_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(40);
            Property(x => x.CiudadBod).HasColumnName(@"ciudad_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(26);
            Property(x => x.EstadoBod).HasColumnName(@"estado_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(4);
            Property(x => x.CodPostBod).HasColumnName(@"cod_post_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(10);
            Property(x => x.PaisBod).HasColumnName(@"pais_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(20);
            Property(x => x.Telef1Bod).HasColumnName(@"telef1_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(20);
            Property(x => x.Telef2Bod).HasColumnName(@"telef2_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(20);
            Property(x => x.Exten1Bod).HasColumnName(@"exten1_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(4);
            Property(x => x.Exten2Bod).HasColumnName(@"exten2_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(4);
            Property(x => x.FaxBod).HasColumnName(@"fax_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(20);
            Property(x => x.EncargadoBod).HasColumnName(@"encargado_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(40);
            Property(x => x.PermMovBod).HasColumnName(@"perm_mov_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(1);
            Property(x => x.TipoBod).HasColumnName(@"tipo_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(1);
            Property(x => x.SubsBod).HasColumnName(@"subs_bod").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(3);
            Property(x => x.Serie).HasColumnName(@"serie").HasColumnType("char").IsOptional().IsFixedLength().IsUnicode(false).HasMaxLength(1);
            Property(x => x.Factura).HasColumnName(@"factura").HasColumnType("decimal").IsOptional().HasPrecision(8,0);
            Property(x => x.OrdenCompra).HasColumnName(@"orden_compra").HasColumnType("decimal").IsOptional().HasPrecision(8,0);
            Property(x => x.Entrada).HasColumnName(@"entrada").HasColumnType("decimal").IsOptional().HasPrecision(8,0);
            Property(x => x.Salida).HasColumnName(@"salida").HasColumnType("decimal").IsOptional().HasPrecision(8,0);
            Property(x => x.TranInv).HasColumnName(@"tran_inv").HasColumnType("decimal").IsOptional().HasPrecision(8,0);
            Property(x => x.Cotizacion).HasColumnName(@"cotizacion").HasColumnType("decimal").IsOptional().HasPrecision(8,0);
        }
    }

}
// </auto-generated>
