// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Avika.Forum.Model
{

    // NewHasPhotos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.0.0")]
    public class NewHasPhoto
    {
        public int Id { get; set; } // Id (Primary key)
        public int NewId { get; set; } // NewId
        public byte[] NameHistoric { get; set; } // NameHistoric (length: 70)
        public byte[] Namephysical { get; set; } // Namephysical (length: 70)
        public string UserCreatorId { get; set; } // UserCreatorId (length: 128)
        public System.DateTime DateCreation { get; set; } // DateCreation
        public bool Active { get; set; } // Active

        // Foreign keys

        /// <summary>
        /// Parent News pointed by [NewHasPhotos].([NewId]) (FK_NewHasPhotos_News)
        /// </summary>
        public virtual New News { get; set; } // FK_NewHasPhotos_News
    }

}
// </auto-generated>
