// <auto-generated />
namespace Avika.Forum.WebApiAuthorization.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class agregaFechaNacimiento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregaFechaNacimiento));
        
        string IMigrationMetadata.Id
        {
            get { return "201807241516225_agregaFechaNacimiento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
