// <auto-generated />
namespace Avika.Forum.WebApiAuthorization.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class agregaCampoConexion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregaCampoConexion));
        
        string IMigrationMetadata.Id
        {
            get { return "201808171730098_agregaCampoConexion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
